# Generated by Django 4.2.11 on 2026-03-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the ingredient.', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='The amount of the ingredient. (I.E., 5 apples, or 2 liters of milk)', max_digits=10)),
                ('date_obtained', models.DateField(help_text='The date an ingredient is registered.')),
                ('date_expired', models.DateField(help_text='The approximate date an ingredient expires.')),
                ('food_group', models.CharField(choices=[('FR', 'FRUIT'), ('VE', 'VEGETABLE'), ('GR', 'GRAIN'), ('PR', 'PROTEIN'), ('DA', 'DAIRY'), ('SN', 'SNACK'), ('BE', 'BEVERAGE'), ('OT', 'OTHER')], default='FR', max_length=2)),
                ('unit_measurement', models.CharField(choices=[('TSP', 'Teaspoon'), ('TBSP', 'Tablespoon'), ('CUP', 'Cup'), ('OZ', 'Ounce'), ('G', 'Gram'), ('KG', 'Kilogram'), ('ML', 'Milliliter'), ('L', 'Liter'), ('A', 'Amount'), ('LB', 'Pound'), ('BX', 'Boxes'), ('BTL', 'Bottles'), ('CAN', 'Can'), ('CRT', 'Carton'), ('BAGS', 'Bags')], default='TSP', max_length=4)),
            ],
        ),
    ]
