# Generated by Django 4.2.11 on 2026-03-15 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='date_obtained',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date an ingredient is registered.'),
        ),
    ]
