# Generated by Django 4.2.11 on 2026-03-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_ingredient_user_alter_ingredient_date_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_measurement',
            field=models.CharField(choices=[('TSP', 'Teaspoon'), ('TBSP', 'Tablespoon'), ('CUP', 'Cup'), ('OZ', 'Ounce'), ('G', 'Gram'), ('KG', 'Kilogram'), ('ML', 'Milliliter'), ('L', 'Liter'), ('A', 'Amount'), ('LB', 'Pound'), ('BX', 'Boxes'), ('BTL', 'Bottles'), ('CAN', 'Can'), ('CRT', 'Carton'), ('BAGS', 'Bags'), ('UNT', 'Unit')], default='TSP', max_length=4),
        ),
    ]
