# Generated by Django 4.2.11 on 2026-04-13 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0004_alter_ingredient_unit_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-Free', 'Gluten-Free'), ('Dairy-Free', 'Dairy-Free'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Low Carb', 'Low Carb'), ('Halal', 'Halal'), ('Milk-Free', 'Milk-Free'), ('Peanut-Free', 'Peanut-Free'), ('Tree Nut-Free', 'Tree Nut-Free'), ('Egg-Free', 'Egg-Free'), ('Fish-Free', 'Fish-Free'), ('Shellfish-Free', 'Shellfish-Free'), ('Wheat-Free', 'Wheat-Free'), ('Sesame-Free', 'Sesame-Free'), ('Soy-Free', 'Soy-Free'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Dessert', 'Dessert'), ('One Pot', 'One Pot'), ('No Cook', 'No Cook')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'System Tag',
                'verbose_name_plural': 'System Tags',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Represents the name of the recipe.', max_length=100)),
                ('prep_time', models.PositiveIntegerField(help_text='Represents the approximate time a recipe will take to make in minutes.')),
                ('cook_time', models.PositiveIntegerField(help_text="Represents the approximate time a recipe will take to cook. Doesn't neccesarily require the user to be doing anything.")),
                ('description', models.TextField(help_text='Represents the detailed description of a recipe.', max_length=100000)),
                ('tags', models.ManyToManyField(blank=True, to='Inventory.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
