# Generated by Django 4.2.11 on 2026-04-17 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_tag_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_used',
            field=models.TextField(default='', help_text='Comma-separated list of ingredients used.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='', help_text='Step-by-step cooking instructions.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(default='Other', help_text='Recipe category e.g. Dinner, Breakfast.', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=0, help_text='Approximate cook time in minutes.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Detailed description of the recipe.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='Approximate prep time in minutes.'),
        ),
    ]
